#!/usr/bin/env bash 
# displays 1 to 100

k=1
while [ $k((k++) 10 ]; do
	if #!/usr/bin/env bash
# Feel that fuzz, bizz ;-)
i=0
while [ $((i++)) -lt 100 ]; do
	if [ $((i % 15)) -eq 0 ]; then
		echo "FizzBuzz"
	elif [ $((i % 5)) -eq 0 ]; then
		echo "Buzz"
	elif [ $((i % 3)) -eq 0 ]; then
		echo "Fizz"
	else
		echo $i
	fi
done
