#!/usr/bin/env bash
# displays content of /etc/passwd

read_and_cut="/etc/passwd"
while IFS=: read -r f1 f2 f3 f4 f5 f6 f7
do 
	echo "The user $f1 is part of the $f4 gang, lives in $f6 and rides $f7, $f3's
done < "$read_and_cut"
